// AUTO-GENERATED by scripts/generate-modules.mjs — do not edit manually.
import type { ModuleInfo } from "./types";

export const MODULES_VERSION = "2.5.8";
export const MODULES: ModuleInfo[] = [
  {
    "id": "craft-core-achievement",
    "name": "Craft-Core Achievement",
    "description": "Custom server achievements & advancement tracker for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.achievement.CraftCoreAchievementMod"
  },
  {
    "id": "craft-core-afk",
    "name": "Craft-Core AFK Protection",
    "description": "AFK movement detection and protection status (/afk)",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.afk.CraftCoreAfkMod"
  },
  {
    "id": "craft-core-back",
    "name": "Craft-Core Back",
    "description": "Death point and previous location back teleport for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.back.CraftCoreBackMod"
  },
  {
    "id": "craft-core-backup",
    "name": "Craft-Core Auto-Backup",
    "description": "Incremental world auto-backup system with 100GB storage cap (/backup)",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.backup.CraftCoreBackupMod"
  },
  {
    "id": "craft-core-bounty",
    "name": "Craft-Core Bounty",
    "description": "Global server-wide weekly collective goals & bounties manager for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-economy"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.bounty.CraftCoreBountyMod"
  },
  {
    "id": "craft-core-checkin",
    "name": "Craft-Core CheckIn",
    "description": "Pure Java 30-day daily sign-in rewards GUI for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-economy"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.checkin.CraftCoreCheckinMod"
  },
  {
    "id": "craft-core-claims",
    "name": "Craft-Core Land Claims",
    "description": "Land protection, claim purchasing (/claim), trust lists, subclaims, and claim protection mixins.",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.claim.CraftCoreClaimsMod"
  },
  {
    "id": "craft-core-economy",
    "name": "Craft-Core Economy",
    "description": "Economy management, bank checks, and payment system sub-module",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.economy.CraftCoreEconomyMod"
  },
  {
    "id": "craft-core-express",
    "name": "Craft-Core Express",
    "description": "Offline parcel express delivery system (/express) for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.express.CraftCoreExpressMod"
  },
  {
    "id": "craft-core-fakeplayer",
    "name": "Craft-Core FakePlayer",
    "description": "Carpet fake player bot control console and management sub-module for Craft-Core.",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.fakeplayer.CraftCoreFakePlayerMod"
  },
  {
    "id": "craft-core-fish",
    "name": "Craft-Core Fish Codex & Market",
    "description": "Fantasy fishing codex, market, and daily contest (/fish)",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.fish.CraftCoreFishMod"
  },
  {
    "id": "craft-core-home",
    "name": "Craft-Core Home",
    "description": "Personal home management and teleportation for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-back",
      "craft-core-teleport"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.home.CraftCoreHomeMod"
  },
  {
    "id": "craft-core-invsee",
    "name": "Craft-Core Inventory Inspector",
    "description": "Admin inventory and enderchest inspector (/invsee)",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.invsee.CraftCoreInvSeeMod"
  },
  {
    "id": "craft-core-libs",
    "name": "Craft-Core Libs",
    "description": "Compulsory Core Library for Craft-Core Ecosystem providing EconomyAPI, RebrandEngine, LangManager, MenuRegistry, and JsonDataStore.",
    "version": "2.5.8",
    "depends": [],
    "recommends": [],
    "entrypoint": "com.craftcore.CraftCoreLibsMod"
  },
  {
    "id": "craft-core-lobby",
    "name": "Craft-Core Lobby",
    "description": "Lobby and Hub dimension management for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-back",
      "craft-core-teleport"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.lobby.CraftCoreLobbyMod"
  },
  {
    "id": "craft-core-luckydraw",
    "name": "Craft-Core LuckyDraw",
    "description": "Pure Java 9x3 key lottery roulette animation & batch draw for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-economy"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.luckydraw.CraftCoreLuckydrawMod"
  },
  {
    "id": "craft-core-machine",
    "name": "Craft-Core Machine Registry",
    "description": "Auto mining machines certification and land tax exemption (/machine)",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.machine.CraftCoreMachineMod"
  },
  {
    "id": "craft-core-menu",
    "name": "Craft-Core Menu",
    "description": "Central Hub GUI framework (/menu) for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [
      "craft-core-shop",
      "craft-core-checkin",
      "craft-core-luckydraw",
      "craft-core-express",
      "craft-core-fakeplayer"
    ],
    "entrypoint": "com.craftcore.menu.CraftCoreMenuMod"
  },
  {
    "id": "craft-core-mining",
    "name": "Craft-Core Mining",
    "description": "Resource and mining dimension management for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-back",
      "craft-core-teleport"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.mining.CraftCoreMiningMod"
  },
  {
    "id": "craft-core-portable",
    "name": "Craft-Core Portable Menus",
    "description": "Portable Enderchest, Workbench, and Trashcan menus for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.portable.CraftCorePortableMod"
  },
  {
    "id": "craft-core-protection",
    "name": "Craft-Core Lockbox & Protection",
    "description": "Chest lockboxes (/padlock), X-Ray honeypot trap protection, PvP combat toggle (/pvp), and container protection mixins.",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.protection.CraftCoreProtectionMod"
  },
  {
    "id": "craft-core-rewards",
    "name": "Craft-Core Rewards",
    "description": "Rewards & retention ecosystem integration module for Craft-Core",
    "version": "2.5.8",
    "depends": [],
    "recommends": [],
    "entrypoint": "com.craftcore.rewards.CraftCoreRewardsMod"
  },
  {
    "id": "craft-core-rtp",
    "name": "Craft-Core RTP",
    "description": "Random teleportation system for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-back",
      "craft-core-teleport"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.rtp.CraftCoreRtpMod"
  },
  {
    "id": "craft-core-shop",
    "name": "Craft-Core Shop",
    "description": "Chest Shops, Market GUI, Ratings, and Remote Restock sub-module",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [
      "craft-core-economy"
    ],
    "entrypoint": "com.craftcore.shop.CraftCoreShopMod"
  },
  {
    "id": "craft-core-spawn",
    "name": "Craft-Core Spawn",
    "description": "Server spawn point management and teleportation for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-back",
      "craft-core-teleport"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.spawn.CraftCoreSpawnMod"
  },
  {
    "id": "craft-core-task",
    "name": "Craft-Core Task",
    "description": "Daily quests & AI tasks manager with BossBar and Sidebar for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-economy"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.task.CraftCoreTaskMod"
  },
  {
    "id": "craft-core-teleport",
    "name": "Craft-Core Teleport",
    "description": "Base teleportation utilities and core library for Craft-Core",
    "version": "2.5.8",
    "depends": [],
    "recommends": [],
    "entrypoint": "com.craftcore.teleport.CraftCoreTeleportMod"
  },
  {
    "id": "craft-core-tpa",
    "name": "Craft-Core TPA",
    "description": "Player-to-player teleport request system for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-back",
      "craft-core-teleport"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.tpa.CraftCoreTpaMod"
  },
  {
    "id": "craft-core-treasure",
    "name": "Craft-Core Treasure Radar",
    "description": "Wilderness treasure chest spawner and radar locator (/treasure)",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.treasure.CraftCoreTreasureMod"
  },
  {
    "id": "craft-core-utility",
    "name": "Craft-Core Utility Cluster",
    "description": "Aggregate utility module for Craft-Core ecosystem",
    "version": "2.5.8",
    "depends": [],
    "recommends": [],
    "entrypoint": "com.craftcore.utility.CraftCoreUtilityMod"
  },
  {
    "id": "craft-core-vein",
    "name": "Craft-Core Vein Mining",
    "description": "Ore vein mining and tree feller toggle system (/vein)",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.vein.CraftCoreVeinMod"
  },
  {
    "id": "craft-core-warp",
    "name": "Craft-Core Warp",
    "description": "Public warp point management and teleportation for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-back",
      "craft-core-teleport"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.warp.CraftCoreWarpMod"
  },
  {
    "id": "craft-core-world",
    "name": "Craft-Core World",
    "description": "Multi-dimension management and position persistence for Craft-Core",
    "version": "2.5.8",
    "depends": [
      "craft-core-libs",
      "craft-core-back",
      "craft-core-teleport"
    ],
    "recommends": [],
    "entrypoint": "com.craftcore.world.CraftCoreWorldMod"
  }
];

export const MODULES_BY_ID: Record<string, ModuleInfo> = Object.fromEntries(
  MODULES.map((m) => [m.id, m])
);
