import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const publicRoot = path.resolve(__dirname, "../../fabric-mod-public");
const gradlePropsPath = path.join(publicRoot, "gradle.properties");
const dataPath = path.join(root, "lib", "modules-data.ts");

let modVersion = "2.5.8";
if (fs.existsSync(gradlePropsPath)) {
  const raw = fs.readFileSync(gradlePropsPath, "utf8");
  const m = raw.match(/^\s*mod_version\s*=\s*([^\s]+)/m);
  if (m) modVersion = m[1].trim();
}

function walkMods(dir, acc = []) {
  if (!fs.existsSync(dir)) return acc;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkMods(p, acc);
    } else if (entry.name === "fabric.mod.json") {
      acc.push(p);
    }
  }
  return acc;
}

const modJsonFiles = walkMods(publicRoot).filter((p) => p.includes("src") && p.includes("resources"));

const modules = [];
for (const f of modJsonFiles) {
  let json;
  try {
    json = JSON.parse(fs.readFileSync(f, "utf8"));
  } catch (e) {
    console.warn("SKIP (bad json):", f);
    continue;
  }
  if (!json.id) continue;
  const depends =
    json.depends && typeof json.depends === "object"
      ? Object.keys(json.depends).filter((k) => k.startsWith("craft-core-"))
      : [];
  const recommends =
    json.recommends && typeof json.recommends === "object"
      ? Object.keys(json.recommends).filter((k) => k.startsWith("craft-core-"))
      : [];
  const entrypoint =
    json.entrypoints && json.entrypoints.main && json.entrypoints.main.length
      ? json.entrypoints.main[0]
      : "";
  modules.push({
    id: json.id,
    name: json.name || json.id,
    description: json.description || "",
    version: String(json.version || "${version}").replace("${version}", modVersion),
    depends,
    recommends,
    entrypoint,
  });
}

modules.sort((a, b) => a.id.localeCompare(b.id));

if (modules.length === 0 && !fs.existsSync(publicRoot) && fs.existsSync(dataPath)) {
  console.warn("WARN: fabric-mod-public/ not found — keeping existing modules-data.ts unchanged.");
  process.exit(0);
}


const code = `// AUTO-GENERATED by scripts/generate-modules.mjs — do not edit manually.
import type { ModuleInfo } from "./types";

export const MODULES_VERSION = "${modVersion}";
export const MODULES: ModuleInfo[] = ${JSON.stringify(modules, null, 2)};

export const MODULES_BY_ID: Record<string, ModuleInfo> = Object.fromEntries(
  MODULES.map((m) => [m.id, m])
);
`;

fs.mkdirSync(path.dirname(dataPath), { recursive: true });
fs.writeFileSync(dataPath, code, "utf8");
console.log(`Generated ${modules.length} modules @ v${modVersion} -> ${path.relative(root, dataPath)}`);
